export const apiRoute = {
  user: {
    getListUser: 'user/get-list-users',
    getDetailUser: 'user/get-detail-user',
    changeStatus: 'user/change-status-user',
    addNewUser: 'user/add-new-user',
    updateUser: 'user/update-user',
  },
  auth: {
    login: '/auth/login',
    signUp: '/auth/register',
    verifySignUp: '/auth/verify-email',
    logout: '/auth/logout',
    verify2FA: '/auth/verify-2fa',
    forgotPassword: '/auth/forgot-password',
  },
  settings: {
    updatePassword: 'settings/update-password',
    updateGeneralSettings: 'settings/update-general-settings',
    updateAccountSettings: 'settings/update-account-settings',
    getGeneralSettings: 'settings/get-general-settings',
  },
  permissions: {
    updatePermission: 'permission/update-permission',
    deletePermission: 'permission/delete-permission',
    addPermission: 'permission/add-new-permission',
    getListPermission: '/permission/get-list-permissions',
    getViewPointsSelect: '/permission/get-view-points-select',
    getDetailPermission: '/permission/get-detail-permission',
    getEditableSelect: '/permission/get-editable-select',
  },
  feature: {
    getFeatureList: 'feature/get-list-feature',
    changeStatusFeature: 'feature/change-status',
  },
  message: {
    toChatRoom: 'message/to-chat-room',
    outChatRoom: 'message/out-chat-room',
    sendMessage: 'message/send-message',
    onlineUser: 'message/online-users',
    getLastMessage: 'message/get-last-messages',
    getOldMessage: 'message/get-old-messages',
    getChatRooms: 'message/get-chat-room',
  },
  language: {
    getLanguageSelectList: 'language/get-language-select-list',
    getLanguageList: 'language/get-language-list',
    getLanguageByKey: 'language/get-language-by-key',
    addNewLanguage: 'language/add-new-language',
    updateLanguage: 'language/update-language',
    addNewDictionary: 'language/add-new-dictionary',
    deleteDictionaryKey: 'language/delete-dictionary-key',
    updateDictionaryList: 'language/update-dictionary-list',
  },
}
